# Numenta.org Jekyll Config
# http://jekyllrb.com/docs/configuration/

### about

description:  Numenta Platform for Intelligent Computing
name:         NuPIC
tagline:      Numenta Platform for Intelligent Computing
title:        NuPIC
copyright:    Copyright © 2015 Numenta
company:      Numenta

### paths

data_source:  ./_data
destination:  ./_site
#include_dir: ./_includes # jekyll lock
layouts:      ./_layouts
plugins:      ./_plugins
sass_dir:     ./_sass
source:       . # gh-pages lock

### settings

encoding:     utf-8
future:       false
gems:         [ 'jekyll-redirect-from' ]
highlighter:  pygments
lsi:          false # gh-pages lock
markdown:     kramdown
safe:         true # gh-pages lock
timezone:     America/Los_Angeles

### inclusions/exclusions

#include:
exclude:
  - _config.yml
  - CNAME
  - Gemfile
  - Gemfile.lock
  - npm-debug.log
  - package.json
  - README.md
  - _data/
  - _includes/
  - _layouts/
  - _sass/
  - _site/
  - node_modules/kss/

### plugins

kramdown:
  input: GFM  # github-flavor

syntax-highlighting:
  enabled: true

### yaml defaults

# defaults:

### collections http://jekyllrb.com/docs/collections/

# collections:
