# Numenta.org Jekyll Config
# http://jekyllrb.com/docs/configuration/

### about

baseurl:    /numenta.org  # http://numenta.org

title:      NuPIC
tagline:    Numenta Platform for Intelligent Computing

company:    Numenta
copyright:  Copyright © 2015 Numenta

### paths

data_source:  ./_data
destination:  ./_site
#include_dir: ./_includes # jekyll lock
layouts:      ./_layouts
plugins:      ./_plugins
sass_dir:     ./_sass
source:       . # gh-pages lock

### settings

encoding:     'utf-8'
future:       true # events
gems:         [ 'jekyll-redirect-from' ]
highlighter:  pygments
lsi:          false # gh-pages lock
markdown:     kramdown
safe:         true # gh-pages lock
timezone:     America/Los_Angeles

### plugins

kramdown:
  hard_wrap: false
  input: GFM # github-flavor

syntax-highlighting:
  enabled: true

### inclusions/exclusions

#include:
exclude:
  - _config.yml
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - npm-debug.log
  - package.json
  - README.md
  - _data/
  - _includes/
  - _layouts/
  - _sass/
  - _site/
  - node_modules/.bin/
  - node_modules/check-pages/
  - node_modules/gulp/
  - node_modules/gulp-cli/
  - node_modules/gulp-webserver/
  - node_modules/kss/
