#
# Numenta.org GitHub Pages Jekyll Config
# http://jekyllrb.com/docs/configuration/
#

### about

#baseurl: http://numenta.org   # production
baseurl: /numenta.org          # staging
#baseurl:                      # development

title:      NuPIC
tagline:    Numenta Platform for Intelligent Computing

company:    Numenta
copyright:  Copyright © 2015 Numenta

### paths

data_source:  ./_data
destination:  ./_site
#include_dir: ./_includes # gh-pages
layouts:      ./_layouts
plugins:      ./_plugins
sass_dir:     ./_sass
source:       . # gh-pages

### settings

encoding:     'utf-8'
future:       true # events
gems:         [ 'jekyll-redirect-from' ]
highlighter:  pygments
lsi:          false # gh-pages
markdown:     kramdown
safe:         true # gh-pages
timezone:     America/Los_Angeles

### plugins

kramdown:
  hard_wrap: false
  input: GFM # github-flavor

syntax-highlighting:
  enabled: true

### inclusions/exclusions

exclude:
- "_config.yml"
- "CNAME"
- "Gemfile"
- "Gemfile.lock"
- "gulpfile.js"
- "npm-debug.log"
- "package.json"
- "README.md"
- "_data"
- "_includes"
- "_layouts"
- "_sass"
- "_site"
- "node_modules"
- "vendor"
